### ISSUE TITLE
Choose number of workers for multiprocessing (AMS + af-AMS) 

### ISSUE THREAD

**Issue by PierreLaville** [huguesrichard/Allopipe#27]
Currently: takes all available.
Todo: set number of workers as an argument (default: all ; all - 1 ; all - X ?)

Set with `max_workers=XX`: Ex. `ProcessPoolExecutor(max_workers=12)`
https://github.com/huguesrichard/Allopipe/blob/660b3ff2a2d408e61a8dea9dea6195f89bf1af93/src/multiprocess_ams.py#L97

**Comment by huguesrichard** [comment]
let's decide on a default value of half of the available cores and add one argument in the command line.
