### ISSUE TITLE
Pandas v2 (> 1.5.0) incompatibility

### ISSUE THREAD

**Issue by PierreLaville** [huguesrichard/Allopipe#3]
Error is:

> Error:"ValueError: invalid literal for int() with base 10: ''

_Originally posted by @huguesrichard in https://github.com/huguesrichard/Allopipe/issues/2#issuecomment-1892769351_

**Comment by huguesrichard** [comment]
The version number is now fixed in the installation process but the issue should be addressed in a future release.
