### ISSUE TITLE
Add argument to choose number of threads used in multiprocess

### ISSUE THREAD

**Issue by PierreLaville** [huguesrichard/Allopipe#38]
- Why? : because of an excessive amount of RAM used (large files loaded?) which leads to stop computation (`Killed`)
- Solution (doesn't solve the cause): limit the number of threads used in multiprocess (default is **all of them**)
- Example: https://github.com/huguesrichard/Allopipe/blob/c735c7559a709ab84dcc12598092489e56c4b43e/src/multiprocess_ams.py#L97

Replace with:
`    with concurrent.futures.ProcessPoolExecutor(max_workers=12) as executor:` for 12 threads (use variable with argument value instead)

**Comment by huguesrichard** [comment]
I think this is a very good idea. Would there be a way to read the amount of possible threads and fix it to half of it by default?
