### ISSUE TITLE
Fix version number for all dependencies (was: Numpy v2 incompatibility)

### ISSUE THREAD

**Issue by PierreLaville** [huguesrichard/Allopipe#41]
Issue with current version 2.0.2 since the release of version 2.0.0 in 23 May, 2024.
No error with version 1.26.4. 

Error when running example `ams_pipeline.py` :
> `ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

We should consider setting fixed versions for all packages and test upgrades regularly to stay up to date.

**Comment by huguesrichard** [comment]
I am reopening the issue, because we do not test explicitly the version number of all dependencies
