### ISSUE TITLE
upgrade version compatibility for Pandas + Numpy

### ISSUE THREAD

**Issue by huguesrichard** [huguesrichard/Allopipe#50]
Related to issue #41  and #3 , we would like to have the most up to date version for at least pandas and numpy

**Comment by PierreLaville** [comment]
Forgot to push in a separate branch and add a PR.
(see commit https://github.com/huguesrichard/Allopipe/commit/b4a6cad6aea8f2d648ca85a1c17f916f9f2ca1a4)
