### ISSUE TITLE
`--full` argument still used?

### ISSUE THREAD

**Issue by PierreLaville** [huguesrichard/Allopipe#56]
Only occurrence here: https://github.com/huguesrichard/Allopipe/blob/ef8e20ac2a6779b36d7f387fff01a99fa5ba0772/src/tools/helpers_NANOPORE.py#L92

If not delete this argument.

**Comment by huguesrichard** [comment]
I agree we can delete this argument, also the `helpers_NANOPORE` are not really needed anymore in the code I think
